/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_tue_fingerpaint_server_simulator_NativeCommunicator */

#ifndef _Included_nl_tue_fingerpaint_server_simulator_NativeCommunicator
#define _Included_nl_tue_fingerpaint_server_simulator_NativeCommunicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_tue_fingerpaint_server_simulator_NativeCommunicator
 * Method:    simulate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_nl_tue_fingerpaint_server_simulator_NativeCommunicator_simulate
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
